export {default as Layout} from './Layout.vue'
export {default as HomeView} from './HomeView.vue'
export {default as AboutView} from './AboutView.vue'
export {default as CategoryView} from './CategoryView.vue'
export {default as CourseView} from './CourseView.vue'
export {default as TestDialog} from './TestDialog.vue'
